"""Add models

Revision ID: 2e11f1c7422d
Revises: 
Create Date: 2020-04-05 16:17:35.166541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e11f1c7422d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('did', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_index(op.f('ix_day_date'), 'day', ['date'], unique=False)
    op.create_index(op.f('ix_day_timestamp'), 'day', ['timestamp'], unique=False)
    op.create_table('store',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('store_type', sa.String(length=140), nullable=True),
    sa.Column('store_type_description', sa.String(length=140), nullable=True),
    sa.Column('contact', sa.String(length=140), nullable=True),
    sa.Column('payment', sa.String(length=140), nullable=True),
    sa.Column('city', sa.String(length=140), nullable=True),
    sa.Column('sector', sa.String(length=140), nullable=True),
    sa.Column('coverage', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_store_city'), 'store', ['city'], unique=False)
    op.create_index(op.f('ix_store_contact'), 'store', ['contact'], unique=True)
    op.create_index(op.f('ix_store_coverage'), 'store', ['coverage'], unique=False)
    op.create_index(op.f('ix_store_description'), 'store', ['description'], unique=False)
    op.create_index(op.f('ix_store_name'), 'store', ['name'], unique=True)
    op.create_index(op.f('ix_store_payment'), 'store', ['payment'], unique=False)
    op.create_index(op.f('ix_store_sector'), 'store', ['sector'], unique=False)
    op.create_index(op.f('ix_store_store_type'), 'store', ['store_type'], unique=False)
    op.create_index(op.f('ix_store_timestamp'), 'store', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_timestamp'), table_name='store')
    op.drop_index(op.f('ix_store_store_type'), table_name='store')
    op.drop_index(op.f('ix_store_sector'), table_name='store')
    op.drop_index(op.f('ix_store_payment'), table_name='store')
    op.drop_index(op.f('ix_store_name'), table_name='store')
    op.drop_index(op.f('ix_store_description'), table_name='store')
    op.drop_index(op.f('ix_store_coverage'), table_name='store')
    op.drop_index(op.f('ix_store_contact'), table_name='store')
    op.drop_index(op.f('ix_store_city'), table_name='store')
    op.drop_table('store')
    op.drop_index(op.f('ix_day_timestamp'), table_name='day')
    op.drop_index(op.f('ix_day_date'), table_name='day')
    op.drop_table('day')
    # ### end Alembic commands ###
