"""Add day table model

Revision ID: c1dab5308513
Revises: 
Create Date: 2020-03-21 21:28:01.085211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1dab5308513'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('did', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_index(op.f('ix_day_date'), 'day', ['date'], unique=False)
    op.create_index(op.f('ix_day_timestamp'), 'day', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_day_timestamp'), table_name='day')
    op.drop_index(op.f('ix_day_date'), table_name='day')
    op.drop_table('day')
    # ### end Alembic commands ###
